'use client'

import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Home from './page'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

interface RootProps { }

class RootLayout extends React.Component<RootProps> {
  constructor(props: RootProps) {
    super(props);
  }

  render() {
    return (
      <html lang="en">
        <body><Home></Home></body>
      </html>
    )
  }
}

export default RootLayout;